server:
  port: 8080
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
  application:
    name: payment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_example
    username: postgres
    password: 123456
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      schema: public
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
        default_schema: public
security:
  jwt:
    secret-key: "superstructure12345678901234567890"